import React, { ReactElement as JSX } from 'react';
import { Geist, Geist_Mono } from 'next/font/google';

// ** Styles
import '@/styles/globals.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: [ 'latin' ],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: [ 'latin' ],
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Home | Next.js App',
  description: 'Generated by Next.js',
};

function RootLayout(props: RootLayoutProps): JSX {

  const { children } = props;

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}

export default RootLayout;